project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
commit_message: '[skip ci]'
files:
  - source: /src/main/resources/lang/texts.properties
    translation: /src/main/resources/lang/texts_%locale_with_underscore%.properties
