name: Feature request
description: Suggest an idea for this project (search for duplicates first)
labels: "new feature"
body:
 - type: textarea
   attributes:
    label: Use cases
    description: Describe possible situations where this feature could be useful and/or new possibilities it could unlock
    placeholder: This function could help when working with...
   validations:
    required: true
 - type: textarea
   attributes:
    label: Possible implementation
    description: Explain how you see this feature being implemented
 - type: textarea
   attributes:
    label: Visual example(s)
    description: If desired, attach sketches/edited screenshots showing how you expect the feature to appear/get accessed
    placeholder: https://github.com/<username>/<project_name>
 - type: textarea
   attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here
